# Generated by Django 6.0.3 on 2026-03-15 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('rating', models.IntegerField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MetroLine',
            fields=[
                ('line_id', models.AutoField(primary_key=True, serialize=False)),
                ('line_name', models.CharField(max_length=100)),
                ('line_color', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('route_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_stations', models.IntegerField()),
                ('total_time_minutes', models.IntegerField()),
                ('interchanges_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('station_id', models.AutoField(primary_key=True, serialize=False)),
                ('station_name', models.CharField(max_length=255)),
                ('platform_number', models.IntegerField()),
                ('station_order', models.IntegerField()),
                ('is_interchange', models.BooleanField(default=False)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.metroline')),
            ],
        ),
        migrations.CreateModel(
            name='RouteStep',
            fields=[
                ('step_id', models.AutoField(primary_key=True, serialize=False)),
                ('step_order', models.IntegerField()),
                ('instruction_text', models.TextField()),
                ('time_from_previous', models.IntegerField()),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.metroline')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.route')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.station')),
            ],
        ),
        migrations.AddField(
            model_name='route',
            name='destination_station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_destinations', to='base.station'),
        ),
        migrations.AddField(
            model_name='route',
            name='source_station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_sources', to='base.station'),
        ),
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('parking_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_slots', models.IntegerField()),
                ('parking_fee_per_hour', models.DecimalField(decimal_places=2, max_digits=6)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.station')),
            ],
        ),
        migrations.CreateModel(
            name='Fare',
            fields=[
                ('fare_id', models.AutoField(primary_key=True, serialize=False)),
                ('token_fare', models.DecimalField(decimal_places=2, max_digits=6)),
                ('smartcard_fare', models.DecimalField(decimal_places=2, max_digits=6)),
                ('destination_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fare_destinations', to='base.station')),
                ('source_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fare_sources', to='base.station')),
            ],
        ),
        migrations.CreateModel(
            name='StationConnection',
            fields=[
                ('connection_id', models.AutoField(primary_key=True, serialize=False)),
                ('travel_time_minutes', models.IntegerField()),
                ('from_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_from', to='base.station')),
                ('to_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_to', to='base.station')),
            ],
        ),
        migrations.CreateModel(
            name='StationGate',
            fields=[
                ('gate_id', models.AutoField(primary_key=True, serialize=False)),
                ('gate_number', models.CharField(max_length=10)),
                ('direction_description', models.TextField()),
                ('nearby_landmark', models.CharField(max_length=255)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.station')),
            ],
        ),
        migrations.CreateModel(
            name='TrainTiming',
            fields=[
                ('timing_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_train_time', models.TimeField()),
                ('last_train_time', models.TimeField()),
                ('frequency_minutes', models.IntegerField()),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.metroline')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.station')),
            ],
        ),
    ]
