# Generated by Django 6.0.3 on 2026-03-18 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_connection'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Connection',
        ),
    ]
