# Generated by Django 6.0.3 on 2026-04-06 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_delete_connection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='platform_number',
        ),
        migrations.AlterField(
            model_name='station',
            name='is_interchange',
            field=models.IntegerField(),
        ),
    ]
